greeting:
  message: this is LOCAL application.yml

spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/daangnClone
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true


server:
  port: 8081